routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');
Route::resource('category', 'CategoryController');

Route::resource('user', 'UserController');
Route::get('/user/{id}/confirm', 'UserController@formConfirm')->name('user.confirm');
Route::put('/user/{id}/confirm', 'UserController@confirm')->name('user.setConfirm');

Route::resource('place', 'PlaceController');

app/Place.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Place extends Model
{
    protected $guarded = [];
    public function photos()
    {
        return $this->hasMany(PlacePhoto::class);
    }

    public function category()
    {
        return $this->belongsTo(Category::class);
    }

    public function district()
    {
        return $this->belongsTo(District::class);
    }
}

app/Http/Controllers/PlaceController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use Illuminate\Support\Str;
use App\Category;
use App\Province;
use App\Place;
use File;
use DB;

class PlaceController extends Controller
{
    public function index()
    {
        $places = Place::with(['photos', 'category', 'district', 'district.regency', 'district.regency.province'])->orderBy('created_at', 'DESC');
        if (request()->q != '') {
            $places = $places->where('name', 'LIKE', '%' . request()->q . '%');
        }
        $places = $places->paginate(10);
        return view('place.index', compact('places'));
    }

    public function create()
    {
        $categories = Category::orderBy('name', 'ASC')->get();
        $provinces = Province::all();
        return view('place.add', compact('provinces', 'categories'));
    }

    public function store(Request $request)
    {
        $this->validate($request, [
            'name' => 'required|string|max:100',
            'category_id' => 'required|exists:categories,id',
            'district_id' => 'required|exists:districts,id',
            'local_ticket_fee' => 'required|integer',
            'int_ticket_fee' => 'required|integer',
            'description' => 'required|string',
            'image' => 'required'
        ]);

        DB::beginTransaction();
        try {
            $place = Place::create([
                'name' => $request->name,
                'category_id' => $request->category_id,
                'district_id' => $request->district_id,
                'local_ticket_fee' => $request->local_ticket_fee,
                'int_ticket_fee' => $request->int_ticket_fee,
                'description' => $request->description,
                'user_id' => auth()->user()->id
            ]);

            $path = storage_path('app/public/image');
            !File::isDirectory($path) ? File::makeDirectory($path):'';
            foreach ($request->image as $key => $image) {
                $name = time() . Str::random(10) . '.' . $image->getClientOriginalExtension();
                $image->storeAs('public/image', $name);
                $place->photos()->create(['name' => $name, 'order' => $key+1]);
            }

            DB::commit();
            return redirect(route('place.index'))->with(['success' => 'Place has been saved']);
        } catch (\Exception $e) {
            DB::rollback();
            return redirect()->back()->with(['error' => $e->getMessage()]);
        }
    }

    public function edit($id)
    {
        $place = Place::with(['district.regency'])->find($id);
        $categories = Category::orderBy('name', 'ASC')->get();
        $provinces = Province::all();
        return view('place.edit', compact('place', 'categories', 'provinces'));
    }

    public function update(Request $request, $id)
    {
        $this->validate($request, [
            'name' => 'required|string|max:100',
            'category_id' => 'required|exists:categories,id',
            'district_id' => 'required|exists:districts,id',
            'local_ticket_fee' => 'required|integer',
            'int_ticket_fee' => 'required|integer',
            'description' => 'required|string'
        ]);

        DB::beginTransaction();
        try {
            $place = Place::find($id);
            $place->update([
                'name' => $request->name,
                'category_id' => $request->category_id,
                'district_id' => $request->district_id,
                'local_ticket_fee' => $request->local_ticket_fee,
                'int_ticket_fee' => $request->int_ticket_fee,
                'description' => $request->description,
            ]);

            $path = storage_path('app/public/image');
            !File::isDirectory($path) ? File::makeDirectory($path):'';
            if ($request->image != '' && count($request->image) > 0) {
                //DELETE OLD IMAGE DATA
                $photos = $place->photos->pluck('name');
                foreach ($photos as $val) {
                    File::exists($path . '/' . $val) ? File::delete($path . '/' . $val):'';
                }
                $place->photos()->delete();

                //INSERT NEW IMAGE
                foreach ($request->image as $key => $image) {
                    $name = time() . Str::random(10) . '.' . $image->getClientOriginalExtension();
                    $image->storeAs('public/image', $name);
                    $place->photos()->create(['name' => $name, 'order' => $key+1]);
                }
            }

            DB::commit();
            return redirect(route('place.index'))->with(['success' => 'Place has been updated']);
        } catch (\Exception $e) {
            DB::rollback();
            return redirect()->back()->with(['error' => $e->getMessage()]);
        }
    }

    public function destroy($id)
    {
        $place = Place::with(['photos'])->find($id);
        $files = $place->photos->pluck('name');
        foreach ($files as $file) {
            File::delete(storage_path('app/public/image/' . $file));
        }
        $place->photos()->delete();
        $place->delete();
        return redirect(route('place.index'))->with(['success' => 'Place has been deleted']);
    }
}

resources/views/place/add.blade.php
@extends('layouts.admin')

@section('title')
    <title>Add New Place</title>
@endsection

@section('css')
    <link href="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.6-rc.0/css/select2.min.css" rel="stylesheet" />
@endsection

@section('content')
    <main role="main" class="col-md-9 ml-sm-auto col-lg-10 px-4">
        <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
            <h1 class="h2">Add New Place</h1>
            <div class="btn-toolbar mb-2 mb-md-0">
                
            </div>
        </div>

        <div class="card">
            <div class="card-body">
                <form action="{{ route('place.store') }}" method="post" enctype="multipart/form-data">
                    @csrf

                    @if (session('error'))
                        <div class="alert alert-danger">{{ session('error') }}</div>
                    @endif

                    <div class="form-group">
                        <label for="">Name</label>
                        <input type="text" name="name" class="form-control {{ $errors->has('name') ? 'is-invalid':'' }}" placeholder="Input Name">
                        <p class="text-danger">{{ $errors->first('name') }}</p>
                    </div>
                    <div class="form-group">
                        <label for="">Category</label>
                        <select name="category_id" class="form-control dw-select2 {{ $errors->has('category_id') ? 'is-invalid':'' }}" required>
                            <option value="">Choose</option>
                            @foreach ($categories as $cat)
                                <option value="{{ $cat->id }}">{{ $cat->name }}</option>
                            @endforeach
                        </select>
                        <p class="text-danger">{{ $errors->first('category_id') }}</p>
                    </div>
                    <div class="form-group">
                        <label>Province</label>
                        <select name="province_id" id="province_id" class="form-control dw-select2 {{ $errors->has('province_id') ? 'is-invalid':'' }}" required>
                            <option value="">Choose Province</option>
                            @foreach ($provinces as $province)
                                <option value="{{ $province->id }}">{{ $province->name }}</option>
                            @endforeach
                        </select>
                        <p class="text-danger">{{ $errors->first('province_id') }}</p>
                    </div>
                    <div class="form-group">
                        <label>Regency</label>
                        <select name="regency_id" id="regency_id" class="form-control dw-select2 {{ $errors->has('regency_id') ? 'is-invalid':'' }}" required>
                            <option value="">Choose Regency</option>
                        </select>
                        <p class="text-danger">{{ $errors->first('regency_id') }}</p>
                    </div>
                    <div class="form-group">
                        <label>District</label>
                        <select name="district_id" id="district_id" class="form-control dw-select2 {{ $errors->has('district_id') ? 'is-invalid':'' }}" required>
                            <option value="">Choose District</option>
                        </select>
                        <p class="text-danger">{{ $errors->first('district_id') }}</p>
                    </div>
                    <div class="form-group">
                        <label for="">Local Fee</label>
                        <input type="number" name="local_ticket_fee" class="form-control {{ $errors->has('local_ticket_fee') ? 'is-invalid':'' }}">
                        <p class="text-danger">{{ $errors->first('local_ticket_fee') }}</p>
                    </div>
                    <div class="form-group">
                        <label for="">International Fee</label>
                        <input type="number" name="int_ticket_fee" class="form-control {{ $errors->has('int_ticket_fee') ? 'is-invalid':'' }}">
                        <p class="text-danger">{{ $errors->first('int_ticket_fee') }}</p>
                    </div>
                    <div class="form-group">
                        <label for="">Description</label>
                        <textarea name="description" id="description" class="form-control" cols="30" rows="10"></textarea>
                        <p class="text-danger">{{ $errors->first('description') }}</p>
                    </div>
                    <div class="form-group">
                        <label for="">Image</label>
                        <input type="file" class="form-control {{ $errors->has('image') ? 'is-invalid':'' }}" name="image[]" required multiple="multiple">
                        <p class="text-danger">{{ $errors->first('image') }}</p>
                    </div>
                    <div class="form-group">
                        <button class="btn btn-primary btn-sm">Save</button>
                    </div>
                </form>
            </div>
        </div>
    </main>
@endsection

@section('js')
    <script src="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.6-rc.0/js/select2.min.js"></script>
    <script src="https://cdn.ckeditor.com/4.11.3/standard/ckeditor.js"></script>
    <script>
        $('.dw-select2').select2();
        CKEDITOR.replace('description');

        $('#province_id').on('change', function() {
            $('#regency_id').empty()
            $.ajax({
                url: '/api/regency?province_id=' + $(this).val(),
                cache: false,
                success: function(html){
                    $('#regency_id').append(`
                        <option value="">Choose Regency</option>
                    `)
                    $.each(html, function(index, item) {
                        $('#regency_id').append(`
                            <option value=`+ item.id +`>`+ item.name +`</option>
                        `)
                    })
                }
            });
        })

        $('#regency_id').on('change', function() {
            $('#district_id').empty()
            $.ajax({
                url: '/api/district?regency_id=' + $(this).val(),
                cache: false,
                success: function(html){
                    $('#district_id').append(`
                        <option value="">Choose District</option>
                    `)
                    $.each(html, function(index, item) {
                        $('#district_id').append(`
                            <option value=`+ item.id +`>`+ item.name +`</option>
                        `)
                    })
                }
            });
        })
    </script>
@endsection

resources/views/place/edit.blade.php
@extends('layouts.admin')

@section('title')
    <title>Edit Place</title>
@endsection

@section('css')
    <link href="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.6-rc.0/css/select2.min.css" rel="stylesheet" />
@endsection

@section('content')
    <main role="main" class="col-md-9 ml-sm-auto col-lg-10 px-4">
        <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
            <h1 class="h2">Edit Place</h1>
            <div class="btn-toolbar mb-2 mb-md-0">
                
            </div>
        </div>

        <div class="card">
            <div class="card-body">
                <form action="{{ route('place.update', $place->id) }}" method="post" enctype="multipart/form-data">
                    @csrf
                    @method('PUT')

                    @if (session('error'))
                        <div class="alert alert-danger">{{ session('error') }}</div>
                    @endif

                    <div class="form-group">
                        <label for="">Name</label>
                        <input type="text" name="name" class="form-control {{ $errors->has('name') ? 'is-invalid':'' }}" placeholder="Input Name" value="{{ $place->name }}">
                        <p class="text-danger">{{ $errors->first('name') }}</p>
                    </div>
                    <div class="form-group">
                        <label for="">Category</label>
                        <select name="category_id" class="form-control dw-select2 {{ $errors->has('category_id') ? 'is-invalid':'' }}" required>
                            <option value="">Choose</option>
                            @foreach ($categories as $cat)
                                <option value="{{ $cat->id }}" {{ $cat->id == $place->category_id ? 'selected':'' }}>{{ $cat->name }}</option>
                            @endforeach
                        </select>
                        <p class="text-danger">{{ $errors->first('category_id') }}</p>
                    </div>
                    <div class="form-group">
                        <label>Province</label>
                        <select name="province_id" id="province_id" class="form-control dw-select2 {{ $errors->has('province_id') ? 'is-invalid':'' }}" required>
                            <option value="">Choose Province</option>
                            @foreach ($provinces as $province)
                                <option value="{{ $province->id }}" {{ $province->id == $place->district->regency->province_id ? 'selected':'' }}>{{ $province->name }}</option>
                            @endforeach
                        </select>
                        <p class="text-danger">{{ $errors->first('province_id') }}</p>
                    </div>
                    <div class="form-group">
                        <label>Regency</label>
                        <select name="regency_id" id="regency_id" class="form-control dw-select2 {{ $errors->has('regency_id') ? 'is-invalid':'' }}" required>
                            <option value="">Choose Regency</option>
                        </select>
                        <p class="text-danger">{{ $errors->first('regency_id') }}</p>
                    </div>
                    <div class="form-group">
                        <label>District</label>
                        <select name="district_id" id="district_id" class="form-control dw-select2 {{ $errors->has('district_id') ? 'is-invalid':'' }}" required>
                            <option value="">Choose District</option>
                        </select>
                        <p class="text-danger">{{ $errors->first('district_id') }}</p>
                    </div>
                    <div class="form-group">
                        <label for="">Local Fee</label>
                        <input type="number" name="local_ticket_fee" class="form-control {{ $errors->has('local_ticket_fee') ? 'is-invalid':'' }}" value="{{ $place->local_ticket_fee }}">
                        <p class="text-danger">{{ $errors->first('local_ticket_fee') }}</p>
                    </div>
                    <div class="form-group">
                        <label for="">International Fee</label>
                        <input type="number" name="int_ticket_fee" class="form-control {{ $errors->has('int_ticket_fee') ? 'is-invalid':'' }}" value="{{ $place->int_ticket_fee }}">
                        <p class="text-danger">{{ $errors->first('int_ticket_fee') }}</p>
                    </div>
                    <div class="form-group">
                        <label for="">Description</label>
                        <textarea name="description" id="description" class="form-control" cols="30" rows="10">{{ $place->description }}</textarea>
                        <p class="text-danger">{{ $errors->first('description') }}</p>
                    </div>
                    <div class="form-group">
                        <label for="">Image</label>
                        <input type="file" class="form-control {{ $errors->has('image') ? 'is-invalid':'' }}" name="image[]" multiple="multiple">
                        <p class="text-danger">{{ $errors->first('image') }}</p>
                        <p class="text-warning">Select image if you want to replace image</p>
                    </div>
                    <div class="form-group">
                        <button class="btn btn-primary btn-sm">Update</button>
                    </div>
                </form>
            </div>
        </div>
    </main>
@endsection

@section('js')
    <script src="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.6-rc.0/js/select2.min.js"></script>
    <script src="https://cdn.ckeditor.com/4.11.3/standard/ckeditor.js"></script>
    <script>
        var regency = {{ $place->district->regency->id }}
        var district = {{ $place->district->id }}

        function loadRegency(province_id) {
            $('#regency_id').empty()
            $.ajax({
                url: '/api/regency?province_id=' + province_id,
                cache: false,
                success: function(html){
                    $('#regency_id').append(`
                        <option value="">Choose Regency</option>
                    `)
                    $.each(html, function(index, item) {
                        let selected = item.id == regency ? 'selected':''
                        $('#regency_id').append(`
                            <option value="`+ item.id +`" `+ selected +`>`+ item.name +`</option>
                        `)
                    })
                }
            });
        }

        function loadDistrict(regency_id) {
            $('#district_id').empty()
            $.ajax({
                url: '/api/district?regency_id=' + regency_id,
                cache: false,
                success: function(html){
                    $('#district_id').append(`
                        <option value="">Choose District</option>
                    `)
                    $.each(html, function(index, item) {
                        let selected = item.id == district ? 'selected':''
                        $('#district_id').append(`
                            <option value="`+ item.id +`" `+ selected +`>`+ item.name +`</option>
                        `)
                    })
                }
            });
        }

        $(document).ready(function() {
            $('.dw-select2').select2();
            CKEDITOR.replace('description');

            loadDistrict(regency)
            loadRegency($('#province_id').val())

            $('#province_id').on('change', function() {
                loadRegency($(this).val())
            })

            $('#regency_id').on('change', function() {
                loadDistrict($(this).val())
            })
        });
    </script>
@endsection

resources/views/place/index.blade.php
@extends('layouts.admin')

@section('title')
    <title>Management Place</title>
@endsection

@section('content')
    <main role="main" class="col-md-9 ml-sm-auto col-lg-10 px-4">
        <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
            <h1 class="h2">Management Place</h1>
            <div class="btn-toolbar mb-2 mb-md-0">
                <a href="{{ route('place.create') }}" class="btn btn-primary btn-sm">Add New</a>
            </div>
        </div>

        <div class="card">
            <div class="card-body">
                <div class="row">
                    <div class="col-md-6">
                        <form action="{{ route('place.index') }}" method="get">
                            <div class="form-group">
                                <input type="text" placeholder="search" name="q" class="form-control">
                            </div>
                        </form>
                    </div>
                    <div class="col-md-12">
                        @if (session('success'))
                            <div class="alert alert-success">{{ session('success') }}</div>
                        @endif
                    </div>
                </div>
                
                <div class="table-responsive">
                    <table class="table table-bordered table-hover">
                        <thead>
                            <tr>
                                <th>#</th>
                                <th>Name</th>
                                <th>Category</th>
                                <th>Location</th>
                                <th>Local Fee</th>
                                <th>Int Fee</th>
                                <th>Created at</th>
                                <th>Actions</th>
                            </tr>
                        </thead>
                        @forelse($places as $key => $row)
                        <tr>
                            <td>
                                <img src="{{ asset('storage/image/' . $row->photos[0]->name) }}" alt="{{ $row->name }}" width="100px" height="80px">
                            </td>
                            <td><strong>{{ $row->name }}</strong></td>
                            <td>{{ $row->category->name }}</td>
                            <td>{{ $row->district->name }}, {{ $row->district->regency->name }}, {{ $row->district->regency->province->name }}</td>
                            <td>Rp {{ number_format($row->local_ticket_fee) }}</td>
                            <td>Rp {{ number_format($row->int_ticket_fee) }}</td>
                            <td>{{ $row->created_at }}</td>
                            <td>
                                <form action="{{ route('place.destroy', $row->id) }}" method="post">
                                    @csrf
                                    @method('DELETE')

                                    <a href="{{ route('place.edit', $row->id) }}" class="btn btn-warning btn-sm">Edit</a>
                                    <button class="btn btn-danger btn-sm confirm-delete">Remove</button>
                                </form>
                            </td>
                        </tr>
                        @empty
                        <tr>
                            <td class="text-center" colspan="8">No Data</td>
                        </tr>
                        @endforelse
                    </table>
                </div>
                <div class="float-right">
                    {!! $places->links() !!}
                </div>
            </div>
        </div>
    </main>
@endsection

@section('js')
    <script src="https://unpkg.com/sweetalert/dist/sweetalert.min.js"></script>
    <script>
        $(document).ready(function() {
            $('.confirm-delete').on('click', function(event) {
                event.preventDefault();
                swal({
                    title: "Are you sure?",
                    text: "Once deleted, you will not be able to recover it!",
                    icon: "warning",
                    buttons: true,
                    dangerMode: true,
                })
                .then((willDelete) => {
                    if (willDelete) {
                        $(this).closest('form').submit();
                    }
                });
            })
        })
    </script>
@endsection