routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');
Route::resource('category', 'CategoryController');

Route::resource('user', 'UserController');
Route::get('/user/{id}/confirm', 'UserController@formConfirm')->name('user.confirm');
Route::put('/user/{id}/confirm', 'UserController@confirm')->name('user.setConfirm');

Route::resource('place', 'PlaceController');

app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password', 'role', 'district_id', 'phone_number', 'status'
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];

    public function getRoleAttribute($value)
    {
        if ($value == 1) {
            return 'Administrator';
        } elseif ($value == 2) {
            return 'District Government';
        }
        return 'Maintener';
    }

    public function scopeActive($query)
    {
        return $query->where('status', 1);
    }

    public function scopePending($query)
    {
        return $query->where('status', 0);
    }

    public function setPasswordAttribute($value)
    {
        $this->attributes['password'] = bcrypt($value);
    }

    public function district()
    {
        return $this->belongsTo(District::class);
    }
}

app/Http/Controllers/UserController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Mail\ConfirmMail;
use App\Province;
use App\User;
use Mail;

class UserController extends Controller
{
    public function index()
    {
        $users = User::orderBy('created_at', 'DESC');
        if (request()->status == 'active') {
            $users = $users->active();
        } elseif (request()->status == 'pending') {
            $users = $users->pending();
        }
        $users = $users->paginate(10);
        return view('user.index', compact('users'));
    }

    public function create()
    {
        $provinces = Province::all();
        return view('user.create', compact('provinces'));
    }

    public function store(Request $request)
    {
        $this->validate($request, [
            'name' => 'required|string|max:255',
            'email' => 'required|string|email|max:255|unique:users',
            'password' => 'required|string|min:8|confirmed',
            'phone_number' => 'required|string|max:13',
            'role' => 'required',
            'district_id' => 'required|exists:districts,id'
        ]);

        User::create([
            'name' => $request->name,
            'email' => $request->email,
            'password' => $request->password,
            'phone_number' => $request->phone_number,
            'role' => $request->role,
            'district_id' => $request->district_id,
            'status' => 1
        ]);
        return redirect(route('user.index'))->with(['success' => 'Add User successfully']);
    }

    public function edit($id)
    {
        $user = User::with(['district', 'district.regency'])->find($id);
        $provinces = Province::all();
        return view('user.edit', compact('user', 'provinces'));
    }

    public function update(Request $request, $id)
    {
        $this->validate($request, [
            'name' => 'required|string|max:255',
            'email' => 'required|string|email|max:255|exists:users',
            'password' => 'nullable|string|min:8|confirmed',
            'phone_number' => 'required|string|max:13',
            'role' => 'required',
            'district_id' => 'required|exists:districts,id'
        ]);

        $user = User::find($id);
        $user->name = $request->name;
        if ($request->password != '') {
            $user->password = $request->password;
        }
        $user->phone_number = $request->phone_number;
        $user->role = $request->role;
        $user->district_id = $request->district_id;
        $user->save();
        return redirect(route('user.index'))->with(['success' => 'Update User successfully']);
    }

    public function destroy($id)
    {
        $user = User::find($id);
        $user->delete();
        return redirect(route('user.index'))->with(['success' => 'Delete User successfully']);
    }

    public function formConfirm($id)
    {
        $user = User::with(['district', 'district.regency', 'district.regency.province'])->find($id);
        return view('user.confirm', compact('user'));
    }

    public function confirm(Request $request, $id)
    {
        $user = User::find($id);
        $user->update(['status' => 1]);
        if ($request->send_email == 1) {
            Mail::to($user->email)->send(new ConfirmMail($user));
        }
        return redirect(route('user.index'))->with(['success' => 'User Confirmed successfully']);
    }
}

resources/views/user/confirm.blade.php
@extends('layouts.admin')

@section('title')
    <title>Confirm User</title>
@endsection

@section('css')
    <link href="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.6-rc.0/css/select2.min.css" rel="stylesheet" />
@endsection

@section('content')
    <main role="main" class="col-md-9 ml-sm-auto col-lg-10 px-4">
        <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
            <h1 class="h2">Confirm User</h1>
            <div class="btn-toolbar mb-2 mb-md-0">
                
            </div>
        </div>

        <div class="card">
            <div class="card-body">
                <div class="table-responsive">
                    <table class="table table-hover table-bordered">
                        <thead>
                            <tr>
                                <th>Name</th>
                                <th>Email</th>
                                <th>Phone Number</th>
                                <th>Role</th>
                                <th>Location</th>
                                <th>Registered At</th>
                            </tr>
                        </thead>
                        <tbody>
                            <tr>
                                <td>{{ $user->name }}</td>
                                <td>{{ $user->email }}</td>
                                <td>{{ $user->phone_number }}</td>
                                <td>{{ $user->role }}</td>
                                <td>{{ $user->district->name }} - {{ $user->district->regency->name }} - {{ $user->district->regency->province->name }}</td>
                                <td>{{ $user->created_at }}</td>
                            </tr>
                        </tbody>
                    </table>
                </div>
                <div class="float-right">
                    <form action="{{ route('user.setConfirm', $user->id) }}" method="post">
                        @csrf
                        @method('PUT')
                        <div class="form-group">
                            <input type="checkbox" name="send_email" value="1"> Send Notification?
                        </div>
                        <div class="form-grou">
                            <button class="btn btn-primary btn-sm">Confirm</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </main>
@endsection

resources/views/user/create.blade.php
@extends('layouts.admin')

@section('title')
    <title>Add New User</title>
@endsection

@section('css')
    <link href="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.6-rc.0/css/select2.min.css" rel="stylesheet" />
@endsection

@section('content')
    <main role="main" class="col-md-9 ml-sm-auto col-lg-10 px-4">
        <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
            <h1 class="h2">Add New User</h1>
            <div class="btn-toolbar mb-2 mb-md-0">
                
            </div>
        </div>

        <div class="card">
            <div class="card-body">
                <form action="{{ route('user.store') }}" method="post">
                    @csrf
                    <div class="form-group">
                        <label for="">Name</label>
                        <input type="text" name="name" class="form-control {{ $errors->has('name') ? 'is-invalid':'' }}" required>
                        <p class="text-danger">{{ $errors->first('name') }}</p>
                    </div>
                    <div class="form-group">
                        <label for="">Email</label>
                        <input type="email" name="email" class="form-control {{ $errors->has('email') ? 'is-invalid':'' }}" required>
                        <p class="text-danger">{{ $errors->first('email') }}</p>
                    </div>
                    <div class="form-group">
                        <label for="">Phone Number</label>
                        <input type="text" name="phone_number" class="form-control {{ $errors->has('phone_number') ? 'is-invalid':'' }}" required>
                        <p class="text-danger">{{ $errors->first('phone_number') }}</p>
                    </div>
                    <div class="form-group">
                        <label for="">Password</label>
                        <input type="password" name="password" class="form-control {{ $errors->has('password') ? 'is-invalid':'' }}" required>
                        <p class="text-danger">{{ $errors->first('password') }}</p>
                    </div>
                    <div class="form-group">
                        <label for="">Password Confirmation</label>
                        <input type="password" name="password_confirmation" class="form-control {{ $errors->has('password_confirmation') ? 'is-invalid':'' }}" required>
                        <p class="text-danger">{{ $errors->first('password_confirmation') }}</p>
                    </div>
                    <div class="form-group">
                        <label for="">Role</label>
                        <select name="role" class="form-control dw-select2 {{ $errors->has('role') ? 'is-invalid':'' }}" required>
                            <option value="">Choose Role</option>
                            <option value="2">District Government</option>
                            <option value="3">Maintener</option>
                        </select>
                        <p class="text-danger">{{ $errors->first('role') }}</p>
                    </div>
                    <div class="form-group">
                        <label>Province</label>
                        <select name="province_id" id="province_id" class="form-control dw-select2 {{ $errors->has('province_id') ? 'is-invalid':'' }}" required>
                            <option value="">Choose Province</option>
                            @foreach ($provinces as $province)
                                <option value="{{ $province->id }}">{{ $province->name }}</option>
                            @endforeach
                        </select>
                        <p class="text-danger">{{ $errors->first('province_id') }}</p>
                    </div>
                    <div class="form-group">
                        <label>Regency</label>
                        <select name="regency_id" id="regency_id" class="form-control dw-select2 {{ $errors->has('regency_id') ? 'is-invalid':'' }}" required>
                            <option value="">Choose Regency</option>
                        </select>
                        <p class="text-danger">{{ $errors->first('regency_id') }}</p>
                    </div>
                    <div class="form-group">
                        <label>District</label>
                        <select name="district_id" id="district_id" class="form-control dw-select2 {{ $errors->has('district_id') ? 'is-invalid':'' }}" required>
                            <option value="">Choose District</option>
                        </select>
                        <p class="text-danger">{{ $errors->first('district_id') }}</p>
                    </div>
                    <div class="form-group">
                        <button class="btn btn-primary btn-sm">Save</button>
                    </div>
                </form>
            </div>
        </div>
    </main>
@endsection

@section('js')
    <script src="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.6-rc.0/js/select2.min.js"></script>
    <script>
        $(document).ready(function() {
            $('.dw-select2').select2();

            $('#province_id').on('change', function() {
                $('#regency_id').empty()
                $.ajax({
                    url: '/api/regency?province_id=' + $(this).val(),
                    cache: false,
                    success: function(html){
                        $('#regency_id').append(`
                            <option value="">Choose Regency</option>
                        `)
                        $.each(html, function(index, item) {
                            $('#regency_id').append(`
                                <option value=`+ item.id +`>`+ item.name +`</option>
                            `)
                        })
                    }
                });
            })

            $('#regency_id').on('change', function() {
                $('#district_id').empty()
                $.ajax({
                    url: '/api/district?regency_id=' + $(this).val(),
                    cache: false,
                    success: function(html){
                        $('#district_id').append(`
                            <option value="">Choose District</option>
                        `)
                        $.each(html, function(index, item) {
                            $('#district_id').append(`
                                <option value=`+ item.id +`>`+ item.name +`</option>
                            `)
                        })
                    }
                });
            })
        });
    </script>
@endsection

resources/views/user/edit.blade.php
@extends('layouts.admin')

@section('title')
    <title>Edit User</title>
@endsection

@section('css')
    <link href="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.6-rc.0/css/select2.min.css" rel="stylesheet" />
@endsection

@section('content')
    <main role="main" class="col-md-9 ml-sm-auto col-lg-10 px-4">
        <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
            <h1 class="h2">Edit User</h1>
            <div class="btn-toolbar mb-2 mb-md-0">
                
            </div>
        </div>

        <div class="card">
            <div class="card-body">
                <form action="{{ route('user.update', $user->id) }}" method="post">
                    @csrf
                    @method('PUT')

                    <div class="form-group">
                        <label for="">Name</label>
                        <input type="text" name="name" class="form-control {{ $errors->has('name') ? 'is-invalid':'' }}" value="{{ $user->name }}" required>
                        <p class="text-danger">{{ $errors->first('name') }}</p>
                    </div>
                    <div class="form-group">
                        <label for="">Email</label>
                        <input type="email" name="email" class="form-control {{ $errors->has('email') ? 'is-invalid':'' }}" value="{{ $user->email }}" required readonly>
                        <p class="text-danger">{{ $errors->first('email') }}</p>
                    </div>
                    <div class="form-group">
                        <label for="">Phone Number</label>
                        <input type="text" name="phone_number" class="form-control {{ $errors->has('phone_number') ? 'is-invalid':'' }}" value="{{ $user->phone_number }}" required>
                        <p class="text-danger">{{ $errors->first('phone_number') }}</p>
                    </div>
                    <div class="form-group">
                        <label for="">Password</label>
                        <input type="password" name="password" class="form-control {{ $errors->has('password') ? 'is-invalid':'' }}">
                        <p class="text-danger">{{ $errors->first('password') }}</p>
                    </div>
                    <div class="form-group">
                        <label for="">Password Confirmation</label>
                        <input type="password" name="password_confirmation" class="form-control {{ $errors->has('password_confirmation') ? 'is-invalid':'' }}">
                        <p class="text-danger">{{ $errors->first('password_confirmation') }}</p>
                    </div>
                    <div class="form-group">
                        <label for="">Role</label>
                        <select name="role" class="form-control dw-select2 {{ $errors->has('role') ? 'is-invalid':'' }}" required>
                            <option value="">Choose Role</option>
                            <option value="2" {{ $user->getOriginal('role') == 2 ? 'selected':'' }}>District Government</option>
                            <option value="3" {{ $user->getOriginal('role') == 3 ? 'selected':'' }}>Maintener</option>
                        </select>
                        <p class="text-danger">{{ $errors->first('role') }}</p>
                    </div>
                    <div class="form-group">
                        <label>Province</label>
                        <select name="province_id" id="province_id" class="form-control dw-select2 {{ $errors->has('province_id') ? 'is-invalid':'' }}" required>
                            <option value="">Choose Province</option>
                            @foreach ($provinces as $province)
                                <option value="{{ $province->id }}" {{ $user->district->regency->province_id == $province->id ? 'selected':'' }}>{{ $province->name }}</option>
                            @endforeach
                        </select>
                        <p class="text-danger">{{ $errors->first('province_id') }}</p>
                    </div>
                    <div class="form-group">
                        <label>Regency</label>
                        <select name="regency_id" id="regency_id" class="form-control dw-select2 {{ $errors->has('regency_id') ? 'is-invalid':'' }}" required>
                            <option value="">Choose Regency</option>
                        </select>
                        <p class="text-danger">{{ $errors->first('regency_id') }}</p>
                    </div>
                    <div class="form-group">
                        <label>District</label>
                        <select name="district_id" id="district_id" class="form-control dw-select2 {{ $errors->has('district_id') ? 'is-invalid':'' }}" required>
                            <option value="">Choose District</option>
                        </select>
                        <p class="text-danger">{{ $errors->first('district_id') }}</p>
                    </div>
                    <div class="form-group">
                        <button class="btn btn-primary btn-sm">Save</button>
                    </div>
                </form>
            </div>
        </div>
    </main>
@endsection

@section('js')
    <script src="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.6-rc.0/js/select2.min.js"></script>
    <script>
        var regency = {{ $user->district->regency->id }}
        var district = {{ $user->district->id }}

        function loadRegency(province_id) {
            $('#regency_id').empty()
            $.ajax({
                url: '/api/regency?province_id=' + province_id,
                cache: false,
                success: function(html){
                    $('#regency_id').append(`
                        <option value="">Choose Regency</option>
                    `)
                    $.each(html, function(index, item) {
                        let selected = item.id == regency ? 'selected':''
                        $('#regency_id').append(`
                            <option value="`+ item.id +`" `+ selected +`>`+ item.name +`</option>
                        `)
                    })
                }
            });
        }

        function loadDistrict(regency_id) {
            $('#district_id').empty()
            $.ajax({
                url: '/api/district?regency_id=' + regency_id,
                cache: false,
                success: function(html){
                    $('#district_id').append(`
                        <option value="">Choose District</option>
                    `)
                    $.each(html, function(index, item) {
                        let selected = item.id == district ? 'selected':''
                        $('#district_id').append(`
                            <option value="`+ item.id +`" `+ selected +`>`+ item.name +`</option>
                        `)
                    })
                }
            });
        }


        $(document).ready(function() {
            $('.dw-select2').select2();
            loadDistrict(regency)
            loadRegency($('#province_id').val())

            $('#province_id').on('change', function() {
                loadRegency($(this).val())
            })

            $('#regency_id').on('change', function() {
                loadDistrict($(this).val())
            })
        });
    </script>
@endsection

resources/views/user/index.blade.php
@extends('layouts.admin')

@section('title')
    <title>Management User</title>
@endsection

@section('css')
    <style>
        a.disabled {
            pointer-events: none;
            cursor: default;
        }
    </style>
@endsection

@section('content')
    <main role="main" class="col-md-9 ml-sm-auto col-lg-10 px-4">
        <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
            <h1 class="h2">Management User</h1>
            <div class="btn-toolbar mb-2 mb-md-0">
                <a href="{{ route('user.create') }}" class="btn btn-primary btn-sm">Add New</a>
            </div>
        </div>

        <div class="card">
            <div class="card-body">
                @if (session('success'))
                    <div class="alert alert-success">{{ session('success') }}</div>
                @endif

                <div class="col-md-4">
                    <form action="{{ route('user.index') }}" method="get">
                        <div class="form-group">
                            <label for="">Filter Status</label>
                            <select name="status" class="form-control">
                                <option value="">Choose Status</option>
                                <option value="pending" {{ request()->status == 'pending' ? 'selected':'' }}>Pending</option>
                                <option value="active" {{ request()->status == 'active  ' ? 'selected':'' }}>Active</option>
                            </select>
                        </div>
                        <div class="form-group">
                            <button class="btn btn-primary btn-sm">Filter</button>
                        </div>
                    </form>
                </div>

                <div class="table-responsive">
                    <table class="table table-bordered table-hover">
                        <thead>
                            <tr>
                                <th>#</th>
                                <th>Name</th>
                                <th>Email</th>
                                <th>Role</th>
                                <th>Status</th>
                                <th>Created at</th>
                                <th>Actions</th>
                            </tr>
                        </thead>
                        @forelse($users as $key => $row)
                        <tr>
                            <td>{{ $key+1 }}</td>
                            <td>{{ $row->name }}</td>
                            <td>{{ $row->email }}</td>
                            <td>{{ $row->role }}</td>
                            <td>
                                @if ($row->status == 1)
                                <span class="badge badge-success">Active</span>
                                @else
                                <span class="badge badge-secondary">Pending</span>
                                @endif
                            </td>
                            <td>{{ $row->created_at }}</td>
                            <td>
                                <form action="{{ route('user.destroy', $row->id) }}" method="post">
                                    @csrf
                                    @method('DELETE')

                                <a href="{{ route('user.confirm', $row->id) }}" class="btn btn-info btn-sm {{ $row->status == 1 ? 'disabled':'' }}">Confirm</a>
                                    <a href="{{ route('user.edit', $row->id) }}" class="btn btn-warning btn-sm">Edit</a>
                                    <button class="btn btn-danger btn-sm confirm-delete">Remove</button>
                                </form>
                            </td>
                        </tr>
                        @empty
                        <tr>
                            <td class="text-center" colspan="7">No Data</td>
                        </tr>
                        @endforelse
                    </table>
                </div>
                <div class="float-right">
                    {!! $users->links() !!}
                </div>
            </div>
        </div>
    </main>
@endsection

@section('js')
    <script src="https://unpkg.com/sweetalert/dist/sweetalert.min.js"></script>
    <script>
        $(document).ready(function() {
            $('.confirm-delete').on('click', function(event) {
                event.preventDefault();
                swal({
                    title: "Are you sure?",
                    text: "Once deleted, you will not be able to recover it!",
                    icon: "warning",
                    buttons: true,
                    dangerMode: true,
                })
                .then((willDelete) => {
                    if (willDelete) {
                        $(this).closest('form').submit();
                    }
                });
            })
        })
    </script>
@endsection